name: contribution-streak-maintainer

on:
  workflow_dispatch:
  schedule:
    # For more information on the cron scheduler,
    # see https://crontab.guru/ or https://crontab.cronhub.io/.
    # This cron schedule means the action runs every day at midnight UTC.
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  contribution-streak-maintainer:
    runs-on: ubuntu-latest
    steps:
      - name: Make a contribution
        run: npx contribution-streak-maintainer ${{github.repository}} --email=roynassif4@gmail.com --condition=10
        env:
          DEVFUL_GITHUB_TOKEN: ${{ secrets.STREAK_MAINTAINER_GITHUB_TOKEN }}
